### PR TITLE
[ADD] script to cast vote

### PR DESCRIPTION
**Pull request by oneskill**

### CODE REVIEW

**Review by fernandoandreotti — APPROVED** [review]
lgtm

**Comment by oneskill** [comment]
> Looks good, but I am getting a: `execution reverted: ERC20Votes: block not yet mined`
> 
> Is this expected?

Yes for the moment, it's totally normal. We have a target block for the ballot at block 8606647, which is not mint yet at the moment.

**Comment by fernandoandreotti** [comment]
Awesome, thanks!

**Comment by ramirolc02** [comment]
await missing on voteTx.wait()(line 34).

**Pull request merged**
